assert(loadfile('work/seat_switch/src/config.lua'))
assert(loadfile('work/seat_switch/src/controller.lua'))
assert(loadfile('work/seat_switch/src/diagnostic_core.lua'))
assert(loadfile('work/seat_switch/src/diagnostic_entry.lua'))
assert(loadfile('work/seat_switch/src/entry.lua'))
assert(loadfile('work/seat_switch/src/module_hash.lua'))
assert(loadfile('work/seat_switch/src/native.lua'))
assert(loadfile('work/seat_switch/src/platform.lua'))
assert(loadfile('work/seat_switch/src/pose.lua'))
assert(loadfile('work/seat_switch/src/policy.lua'))
assert(loadfile('work/seat_switch/src/profile.lua'))
assert(loadfile('work/seat_switch/src/snapshot.lua'))
print("PASS: all Lua source files parse; no native functions executed.")
